### PR TITLE
Fix inadvertent usage of BSL license

### PR DESCRIPTION
**Pull request by coffeexcoin**
It appears the license on the contracts forked from the Optimism Foundation was inadvertently changed to the Business Source License (BSL) from the MIT license.

This PR reverts that change, setting the SPDX-Identifier on the `.sol` files back to MIT.

### CODE REVIEW

**Comment by pop-punk** [comment]
This looks good to me!

**Review by seanmc9 — APPROVED** [review]
lgtm!

**Review by pop-punk — APPROVED** [review]
lgtm!

**Comment by QuitCrypto** [comment]
LGTM 🚢

**Review by QuitCrypto — APPROVED** [review]

**Review by xBA5ED — APPROVED** [review]
lgtm 🚢

**Comment by rookmate** [comment]
Lgtm 🫡

**Pull request closed without merging**
